### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by forntoh** [L-Briand/ShadowLayout#3]
There are **no installation instructions** anywhere
How do I properly install this library?

**Comment by L-Briand** [comment]
Hello,
Since i do not have published the library to any maven repository there is no "simple" way to add it to your project. This is an android Library. You have to clone the repository and then import it in your project.

Clone the repository somewhere :
```
git clone https://github.com/L-Briand/ShadowLayout
```

To reference the external lib project, Insert this 2 lines on `setting.gradle`:
```groovy
include ':ShadowLayout'
project(':ShadowLayout').projectDir = new File('/path-to-lib/ShadowLayout')
```

Then you can add it to the dependencies of your project:
```groovy
dependencies {
    implementation project(':ShadowLayout')
}
```
