### ISSUE TITLE
Installation with gradle

### ISSUE THREAD

**Issue by uszkaisandor** [L-Briand/ShadowLayout#5]
Please, publish this library with jitpack to make installation easier

**Comment by L-Briand** [comment]
Hi @uszkaisandor 

I've hosted the module on maven central. You can check the readme.md for more information.
Since I already have the `net.orandja` space on maven central I have changed the root package from `fr.orandja`to `net.orandja`. You might have to do some refactoring in your codebase if you previously added the `fr.orandja`.
